version = 1
SPDX-PackageName = "fornever.me"
SPDX-PackageSupplier = "fornever.me contributors <https://github.com/ForNeVeR/fornever.me>"
SPDX-PackageDownloadLocation = "https://github.com/ForNeVeR/fornever.me"

[[annotations]]
path = "ForneverMind/posts/*/*.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2013-2025 Friedrich von Never <friedrich@fornever.me>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".idea/**/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Friedrich von Never <friedrich@fornever.me>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "**.DotSettings"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Friedrich von Never <friedrich@fornever.me>"
SPDX-License-Identifier = "MIT"
