name: Release
on:
  push:
    tags:
      - '*'

jobs:
  docker-push:
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Read version from ref
        id: version
        shell: pwsh
        run: echo "version=$(./scripts/Get-Version.ps1 -RefName $env:GITHUB_REF)" >> $env:GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: revenrof/fornever.me:latest,revenrof/fornever.me:${{ steps.version.outputs.version }}
