name: Release
on:
  push:
    tags:
      - '*'

jobs:
  docker-push:
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: revenrof/fornever.me
          tag_with_ref: true
          tags: latest
