name: Release
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # every Sunday

jobs:
  docker-push:
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Read version from ref
        id: version
        shell: pwsh
        run: echo "version=$(./Scripts/Get-Version.ps1 -RefName $env:GITHUB_REF)" >> $env:GITHUB_OUTPUT

      - name: Login to Docker Hub
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') && 'true' || 'false' }}
          tags: revenrof/fornever.me:latest,revenrof/fornever.me:v${{ steps.version.outputs.version }}
